enhance: specify cloze number by {{clozeID xxx}}
debanjandhar12/logseq-anki-sync pull request #250
Opened 2024-01-14 20:47 UTC by e-zz

This PR enables cloze syntax like `{{cloze1 xxx}}`, where the number after keyword `cloze` specifies the display order of the cloze. 
It works the same as `{{c1 xxx}}`. 

Motivation: In logseq, the keyword for cloze macro is `cloze`, instead of `c` in anki style. So maybe it's reasonable to support also parsing `clozeID` syntax. For example, when one wants to force `{{cloze a}}` to appear in the 2nd card, there would be a slight advantage in modifying it to `{{cloze2 a}}` over `{{c2 a}}`.

2024-01-25 17:09 UTC, debanjandhar12 commented
Thank you and sorry for late reply. I check it and found it is not working as expected.

Cards are not created from`{{cloze1 ok}}` as it does not get picked up by getNotesFromLogseqBlocks.

2024-01-25 17:10 UTC, debanjandhar12 requested changes
Thank you and sorry for late reply. I check it and found it is not working as expected.

Cards are not created from{{cloze1 ok}} as it does not get picked up by getNotesFromLogseqBlocks.

2024-01-27 21:26 UTC, e-zz commented
> Thank you and sorry for late reply. I check it and found it is not working as expected.
> 
> When clicking sync button, note is not created from `{{cloze1 ok}}` as it does not get picked up by getNotesFromLogseqBlocks.

Hi, 
Thanks for the test. 
I have patched the PR and now `getNotesFromLogseqBlocks` works well with `{{clozeID }}` syntax.
Cheers!

2024-02-04 07:32 UTC, merged

2024-02-04 07:32 UTC, debanjandhar12 commented
Thanks.

LGTM!